### ISSUE TITLE
failed to serve tls: failed to parse private key

### ISSUE THREAD

**Issue by toien** [purak/gsocks5#1]
i has generated cert and key file following by readme.md and when i start server, encouter this error.

here is env:

```
$ go version
go version go1.12.6 darwin/amd64

$ gsocks5 --version
gsocks5 version 0.1

$ ls $GOPATH/pkg/mod/github.com/buraksezer/gsocks5\@v0.0.0-20180322194832-5e12b3a620d7/
Gopkg.lock Gopkg.toml LICENSE    README.md  client.go  config.go  data       main.go    server.go
```

mac os version is:
Mojave 10.14.3

is it possible something wrong when generate cert/key files? i notice `openssl` ask some params like `passphase` during generation

**Comment by buraksezer** [comment]
Hi,

Are you sure that you set the correct paths for the cert and the key files in server's configuration file?

**Comment by toien** [comment]
yes, both paths are absolute.

i startup program by

```
> gsocks5 -d -c gsocks5-server.json
2019/09/27 00:05:28 [INF] gsocks5: Running as server
2019/09/27 00:05:28 [ERR] gsocks5: failed to serve tls: failed to parse private key
```

gsocks5-server.json: 
```json
{
    "debug": true,
    "role": "server",
    "server_addr": "127.0.0.1:10086",
    "password": "password",
    "server_cert": "/Users/me/gsocks5.cert.pem",
    "server_key": "/Users/me/gsocks5.key.pem"
}
```
gsocks5-server.json (END)

and  GO111MODULE=on, hope this could help

**Comment by buraksezer** [comment]
I created the same error on my computer. It seems that Golang's TLS package changes [something internal](https://github.com/golang/go/issues/10181). Fortunately, I found similar problems and their workarounds on the Internet. 

The following command should fix the problem: 

```
openssl rsa -in key.pem -out unencrypted.key
```

Then, you should use **unencrypted.key** file as **server_key**.

I'm going to update the README file. Thank you for reporting.
